fix(event-bridge): Add state in AWS::Events::Rule (SSPROD-34618)
sysdiglabs/aws-templates-secure-for-cloud pull request #113
Opened 2023-12-18 15:29 UTC by matteopasa

2023-12-18 15:41 UTC, legobrick approved these changes

2023-12-18 16:03 UTC, cgeers requested changes
Similar to how we did it in TF, can we please add this to the parameter list? This setting should remain user configurable, even if the default value is `ENABLED_WITH_ALL_CLOUDTRAIL_MANAGEMENT_EVENTS`. 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html

2023-12-19 15:28 UTC, cgeers approved these changes
looks good!

2023-12-19 16:21 UTC, ravinadhruve10 approved these changes

2023-12-19 16:24 UTC, merged