feat(modules): Support for Govcloud account/org
sysdiglabs/aws-templates-secure-for-cloud pull request #138
Opened 2024-11-14 22:56 UTC by ravinadhruve10

Change summary:
-------------------
- Added support to install govcloud single account and org in foundational template.
- Added same support in log_ingestion event-bridge template.
- For log_ingestion s3, no changes required to the template. Added minor nits.

2024-11-18 18:19 UTC, haresh-suresh approved these changes

2024-11-19 01:02 UTC, nkraemer-sysdig approved these changes

2024-11-19 01:03 UTC, nkraemer-sysdig commented
Please note the [new tagging process](https://github.com/sysdiglabs/aws-templates-secure-for-cloud/pull/137) needed to release CFTs

2024-11-19 15:26 UTC, cgeers requested changes
I don't like the use of a _prefix_ here.  ARNs are not arbitrary strings who's contents we control entirely. AWS dictates the valid format of the ARN, but we're exposing broadly scoped manipulation of the whole ARN string. The basic problem with this can be summarized as "how much of the ARN is being prefixed?" It's not described, users don't know, but then again, nor should they.

Instead this variable should be simply be "partition" with a default value representing commercial.

2024-11-19 22:06 UTC, cgeers approved these changes

2024-11-19 22:25 UTC, jose-pablo-camacho approved these changes

2024-11-19 23:52 UTC, ravinadhruve10 commented
Did another round of testing with latest changes, lgtm!

2024-11-19 23:52 UTC, merged